name: eQTLGenPhase2Env
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - python=3.9.12
  - setuptools
  - r-base=4.2.2
  - r-data.table
  - r-tidyverse
  - coreutils
  - bitarray
  - Cython
  - conda-forge::numpy=1.23.4
  - conda-forge::pandas=1.5.1
  - conda-forge::scipy
  - conda-forge::pyarrow
